# Generated by Django 5.1.2 on 2024-11-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('priority', models.IntegerField()),
                ('resolution', models.CharField(max_length=300, null=True)),
                ('helpdesk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='helpdesks.helpdesk')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.user')),
            ],
        ),
    ]
